// Code generated by docuconf. DO NOT EDIT.
package web

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "web"
		generator: {
			language: "typescript"
			sdk:      "@docuconf/t3"
			version:  "0.1.0"
		}
	}
	vars: {
		CMS_CLIENT: {
			type:        "enum"
			description: "Which CMS provider backs the marketing content client"
			values: ["keystatic", "wordpress"]
			default: "keystatic"
		}
		CONTACT_LEAD_NOTIFY_EMAIL: {
			type:        "string"
			description: "Mailbox notified when the contact form receives a new lead"
		}
		DOCLING_API_KEY: {
			type:        "string"
			description: "Docling API key used to authenticate extraction requests"
			secret:      true
		}
		DOCLING_URL: {
			type:        "url"
			description: "Base URL of the Docling service used to extract document text"
		}
		DOCUMENSO_API_KEY: {
			type:        "string"
			description: "Documenso API key used to create and send documents"
			secret:      true
		}
		DOCUMENSO_URL: {
			type:        "url"
			description: "Base URL of the Documenso instance used for e-signature"
		}
		GOTENBERG_URL: {
			type:        "url"
			description: "Base URL of the Gotenberg service used to render PDFs"
		}
		KEYSTATIC_CONTENT_ROOT: {
			type:        "string"
			description: "Filesystem root Keystatic reads marketing content from"
		}
		NANGO_GMAIL_INTEGRATION_ID: {
			type:        "string"
			description: "Nango integration id for Gmail mailbox connections"
		}
		NANGO_GOOGLE_CALENDAR_INTEGRATION_ID: {
			type:        "string"
			description: "Nango integration id for Google Calendar connections"
		}
		NANGO_HOST: {
			type:        "url"
			description: "Base URL of the Nango instance brokering OAuth connections"
			default:     "http://localhost:3003"
		}
		NANGO_MICROSOFT_CALENDAR_INTEGRATION_ID: {
			type:        "string"
			description: "Nango integration id for Microsoft Calendar connections"
		}
		NANGO_MICROSOFT_INTEGRATION_ID: {
			type:        "string"
			description: "Nango integration id for Microsoft mailbox connections"
		}
		NANGO_SECRET_KEY: {
			type:        "string"
			description: "Nango secret key used to call the Nango server API"
			secret:      true
		}
		NOVU_API_KEY: {
			type:        "string"
			description: "Novu API key used to trigger notification workflows"
			secret:      true
		}
		NOVU_API_URL: {
			type:        "url"
			description: "Base URL of the Novu API the app sends notifications to"
		}
		OTEL_EXPORTER_OTLP_ENDPOINT: {
			type:        "url"
			description: "OTLP collector endpoint traces, metrics and logs are exported to"
		}
		OTEL_SERVICE_NAME: {
			type:        "string"
			description: "Service name attached to exported OpenTelemetry data"
		}
		PYROSCOPE_SERVER_ADDRESS: {
			type:        "url"
			description: "Pyroscope server address continuous profiling data is sent to"
		}
		STRIPE_SECRET_KEY: {
			type:        "string"
			description: "Stripe API secret key used for billing operations"
			required:    true
			secret:      true
			minLength:   1
		}
		STRIPE_WEBHOOK_SECRET: {
			type:        "string"
			description: "Signing secret that verifies inbound Stripe webhooks"
			required:    true
			secret:      true
			minLength:   1
		}
		SUPABASE_DB_WEBHOOK_SECRET: {
			type:        "string"
			description: "Shared secret that signs inbound Supabase database webhooks"
			required:    true
			secret:      true
			minLength:   1
		}
		SUPABASE_SERVICE_ROLE_KEY: {
			type:        "string"
			description: "Supabase service role key used for privileged server-side access"
			required:    true
			secret:      true
			minLength:   1
		}
	}
}
