-- Which permissions each role grants. Global reference data, readable by all
-- authenticated users.

create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  role varchar(50) not null references public.roles (name),
  permission public.app_permissions not null,
  unique (role, permission)
);

alter table public.role_permissions enable row level security;

create index ix_role_permissions_role on public.role_permissions (role);

revoke all on public.role_permissions from authenticated, service_role;
grant select on public.role_permissions to authenticated;
grant select, insert, update, delete on public.role_permissions to service_role;

create policy role_permissions_read on public.role_permissions
  for select to authenticated using (true);

create or replace function public.has_permission(user_id uuid, account_id uuid, permission_name public.app_permissions)
  returns boolean
  language sql security definer
  set search_path = '' as $$
  select exists (
    select 1
    from public.accounts_memberships m
    join public.role_permissions rp on rp.role = m.account_role
    where m.user_id = has_permission.user_id
      and m.account_id = has_permission.account_id
      and rp.permission = has_permission.permission_name
  );
$$;

grant execute on function public.has_permission(uuid, uuid, public.app_permissions) to authenticated, service_role;

-- True when the target user outranks the given role on the account (or is the
-- primary owner). Used to stop a member from granting a role above their own.
create or replace function public.has_more_elevated_role(target_user_id uuid, target_account_id uuid, role_name varchar)
  returns boolean
  language plpgsql security definer
  set search_path = '' as $$
declare
  user_level int;
  role_level int;
begin
  if exists (
    select 1 from public.accounts
    where id = target_account_id and primary_owner_user_id = target_user_id
  ) then
    return true;
  end if;

  select r.hierarchy_level into user_level
  from public.accounts_memberships m
  join public.roles r on r.name = m.account_role
  where m.account_id = target_account_id and m.user_id = target_user_id;

  select hierarchy_level into role_level from public.roles where name = role_name;

  if user_level is null or role_level is null then
    return false;
  end if;

  return user_level < role_level;
end;
$$;

grant execute on function public.has_more_elevated_role(uuid, uuid, varchar) to authenticated, service_role;
