-- Pending invitations to join a team account.

create table if not exists public.invitations (
  id bigint generated by default as identity primary key,
  email varchar(320) not null,
  account_id uuid not null references public.accounts (id) on delete cascade,
  invited_by uuid not null references auth.users on delete cascade,
  role varchar(50) not null references public.roles (name),
  invite_token text not null unique default encode(extensions.gen_random_bytes(24), 'hex'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '7 days',
  constraint invitations_expiry_after_creation check (expires_at > created_at),
  constraint invitations_email_shape check (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
  unique (email, account_id)
);

alter table public.invitations enable row level security;

create index ix_invitations_account on public.invitations (account_id);

revoke all on public.invitations from authenticated, service_role;
grant select, insert, update, delete on public.invitations to service_role;
grant delete on public.invitations to authenticated;
grant update (role, expires_at) on public.invitations to authenticated;
-- invite_token is a credential and is deliberately withheld from the
-- authenticated column grant.
grant select (id, email, account_id, invited_by, role, created_at, updated_at, expires_at)
  on public.invitations to authenticated;

create trigger invitations_timestamps
  before insert or update on public.invitations
  for each row execute function public.set_timestamps();

-- Invitations only make sense for team accounts.
create or replace function tuckin.reject_personal_account_invite()
  returns trigger
  set search_path = '' as $$
begin
  if (select is_personal_account from public.accounts where id = new.account_id) then
    raise exception 'personal accounts cannot have invitations';
  end if;
  return new;
end;
$$ language plpgsql;

create trigger invitations_team_only
  before insert or update on public.invitations
  for each row execute function tuckin.reject_personal_account_invite();

create policy invitations_read on public.invitations
  for select to authenticated
  using (public.has_role_on_account(account_id));

create policy invitations_update on public.invitations
  for update to authenticated
  using (
    public.has_permission((select auth.uid()), account_id, 'invites.manage')
    and public.has_more_elevated_role((select auth.uid()), account_id, role)
  )
  with check (
    public.has_permission((select auth.uid()), account_id, 'invites.manage')
    and public.has_more_elevated_role((select auth.uid()), account_id, role)
  );

create policy invitations_delete on public.invitations
  for delete to authenticated
  using (
    public.has_role_on_account(account_id)
    and public.has_permission((select auth.uid()), account_id, 'invites.manage')
  );

-- Insert invitations for a team, one per (email, role) pair. Service-role only.
create or replace function public.add_invitations_to_account(account_slug text, invites public.invitation[], invited_by uuid)
  returns setof public.invitations
  language plpgsql security definer
  set search_path = '' as $$
declare
  target_account_id uuid;
  invite public.invitation;
begin
  select id into target_account_id from public.accounts where slug = account_slug;

  foreach invite in array invites loop
    return query
    insert into public.invitations (email, account_id, invited_by, role)
    values (invite.email, target_account_id, add_invitations_to_account.invited_by, invite.role)
    returning *;
  end loop;
end;
$$;

grant execute on function public.add_invitations_to_account(text, public.invitation[], uuid) to service_role;

-- Consume a valid token: create the membership and drop the invitation.
create or replace function public.accept_invitation(token text, user_id uuid)
  returns uuid
  language plpgsql security definer
  set search_path = '' as $$
declare
  target_account_id uuid;
  target_role varchar(50);
begin
  select account_id, role into target_account_id, target_role
  from public.invitations
  where invite_token = token and expires_at > now();

  if not found then
    raise exception 'invalid or expired invitation';
  end if;

  insert into public.accounts_memberships (user_id, account_id, account_role)
  values (accept_invitation.user_id, target_account_id, target_role);

  delete from public.invitations where invite_token = token;

  return target_account_id;
end;
$$;

grant execute on function public.accept_invitation(text, uuid) to service_role;
