-- Maps an account to its customer record in a billing provider.

create table if not exists public.billing_customers (
  id bigint generated by default as identity primary key,
  account_id uuid not null references public.accounts (id) on delete cascade,
  provider public.billing_provider not null,
  customer_id text not null,
  email text,
  unique (account_id, provider, customer_id)
);

alter table public.billing_customers enable row level security;

create index ix_billing_customers_account on public.billing_customers (account_id);

revoke all on public.billing_customers from authenticated, service_role;
grant select on public.billing_customers to authenticated;
grant select, insert, update, delete on public.billing_customers to service_role;

-- billing.manage gates read access, so ordinary members never see billing data.
create policy billing_customers_read on public.billing_customers
  for select to authenticated
  using (
    (account_id = (select auth.uid()) and public.is_set('enable_account_billing'))
    or public.has_permission((select auth.uid()), account_id, 'billing.manage')
  );
