// Code generated by docuconf. DO NOT EDIT.
package workers

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind:       "ConfigContract"
	metadata: {
		name: "workers"
		generator: {
			language: "typescript"
			sdk:      "@docuconf/t3"
			version:  "0.1.0"
		}
	}
	vars: {
		DOCLING_API_KEY: {
			type:        "string"
			description: "Docling API key used to authenticate extraction requests"
			secret:      true
		}
		DOCLING_URL: {
			type:        "url"
			description: "Base URL of the Docling service used to extract document text"
		}
		EMAIL_HOST: {
			type:        "string"
			description: "SMTP host the nodemailer mailer connects to"
		}
		EMAIL_PASSWORD: {
			type:        "string"
			description: "SMTP password the nodemailer mailer authenticates with"
			secret:      true
		}
		EMAIL_PORT: {
			type:        "int"
			description: "SMTP port the nodemailer mailer connects to"
			min:         1
			max:         65535
		}
		EMAIL_TLS: {
			type:        "bool"
			description: "Whether the nodemailer mailer connects over TLS"
			default:     true
		}
		EMAIL_USER: {
			type:        "string"
			description: "SMTP username the nodemailer mailer authenticates with"
		}
		MAILER_PROVIDER: {
			type:        "enum"
			description: "Which mailer backend outbound email activities use"
			values: ["nodemailer", "resend"]
			default: "nodemailer"
		}
		NOVU_API_KEY: {
			type:        "string"
			description: "Novu API key used to trigger notification workflows"
			secret:      true
		}
		NOVU_API_URL: {
			type:        "url"
			description: "Base URL of the Novu API the worker sends notifications to"
		}
		RESEND_API_KEY: {
			type:        "string"
			description: "Resend API key the resend mailer sends email with"
			secret:      true
		}
		SUPABASE_SERVICE_ROLE_KEY: {
			type:        "string"
			description: "Supabase service role key used for privileged server-side access"
			required:    true
			secret:      true
			minLength:   1
		}
		TEMPORAL_ADDRESS: {
			type:        "string"
			description: "Host and port of the Temporal frontend the worker connects to"
			default:     "localhost:7233"
		}
		TRIAL_DRIP_FROM_EMAIL: {
			type:        "string"
			description: "From address the trial drip email activity sends with"
		}
	}
}
