{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opendealbook.fullname" . }}
  labels:
    {{- include "opendealbook.labels" . | nindent 4 }}
{{- end }}
