package opendealbook

import (
	"strings"
	"encoding/yaml"
)

// generate.cue turns the structured workloads into templates/workloads.yaml.
// It marshals the concrete objects, then swaps the sentinels planted in
// holes.cue for the real Helm holes. The objects still vet as concrete data
// (cue vet), and the emitted text carries only the allowed holes.

_resources: [
	_web,
	_webService,
	_workers,
	if values.ingress.enabled && values.ingress.type == "ingress" {_ingress},
	if values.ingress.enabled && values.ingress.type == "gateway" {_httpRoute},
]

_stream: yaml.MarshalStream(_resources)

// scalar sentinels (all marshal unquoted); the marketing token carries its
// own surrounding quotes so the env value stays a string.
_s1: strings.Replace(_stream, #holes.image, #holes.tokens[#holes.image], -1)
_s2: strings.Replace(_s1, "\(#holes.replicasWeb)", #holes.tokens["424201"], -1)
_s3: strings.Replace(_s2, "\(#holes.replicasWorkers)", #holes.tokens["424202"], -1)
_s4: strings.Replace(_s3, #holes.fullname, #holes.tokens[#holes.fullname], -1)
_s5: strings.Replace(_s4, #holes.marketing, #holes.tokens[#holes.marketing], -1)

// label/selector map-key sentinels become the include holes at their exact
// marshaled indentation (yaml.Marshal uses 2-space steps). Selector sentinels
// occur at 8, 6 and 4 spaces; replace deepest-first so a shallower pattern
// never eats the trailing spaces of a deeper line.
_l1: strings.Replace(_s5,
	"    \(#holes.labels): \"\"",
	"    {{- include \"opendealbook.labels\" . | nindent 4 }}", -1)

_l2: strings.Replace(_l1,
	"        \(#holes.selector): \"\"",
	"        {{- include \"opendealbook.selectorLabels\" . | nindent 8 }}", -1)

_l3: strings.Replace(_l2,
	"      \(#holes.selector): \"\"",
	"      {{- include \"opendealbook.selectorLabels\" . | nindent 6 }}", -1)

_l4: strings.Replace(_l3,
	"    \(#holes.selector): \"\"",
	"    {{- include \"opendealbook.selectorLabels\" . | nindent 4 }}", -1)

_header: """
	# GENERATED by `make generate` from cue/. DO NOT EDIT BY HAND.
	# Source of truth: cue/workload.cue (+ fixture.cue, holes.cue).

	"""

generated: _header + _l4
